#!/bin/bash

cd /gpfs/home/hdiao/Geombrowser/accu_count

qsub Func_accu_count_0.sh
qsub Func_accu_count_1.sh
qsub Func_accu_count_2.sh
qsub Func_accu_count_3.sh
qsub Func_accu_count_4.sh
qsub Func_accu_count_5.sh
qsub Func_accu_count_6.sh
qsub Func_accu_count_7.sh
qsub Func_accu_count_8.sh
qsub Func_accu_count_9.sh
qsub Func_accu_count_10.sh
qsub Func_accu_count_11.sh
qsub Func_accu_count_12.sh
qsub Func_accu_count_13.sh
qsub Func_accu_count_14.sh
qsub Func_accu_count_15.sh
qsub Func_accu_count_16.sh
qsub Func_accu_count_17.sh
qsub Func_accu_count_18.sh
qsub Func_accu_count_19.sh
qsub Func_accu_count_20.sh
qsub Func_accu_count_21.sh
qsub Func_accu_count_22.sh
qsub Func_accu_count_23.sh
qsub Func_accu_count_24.sh
qsub Func_accu_count_25.sh
qsub Func_accu_count_26.sh
qsub Func_accu_count_27.sh
qsub Func_accu_count_28.sh
qsub Func_accu_count_29.sh
qsub Func_accu_count_30.sh
qsub Func_accu_count_31.sh
qsub Func_accu_count_32.sh
qsub Func_accu_count_33.sh
qsub Func_accu_count_34.sh
qsub Func_accu_count_35.sh
qsub Func_accu_count_36.sh
qsub Func_accu_count_37.sh
qsub Func_accu_count_38.sh
qsub Func_accu_count_39.sh
qsub Func_accu_count_40.sh
qsub Func_accu_count_41.sh
qsub Func_accu_count_42.sh
qsub Func_accu_count_43.sh
qsub Func_accu_count_44.sh
qsub Func_accu_count_45.sh
qsub Func_accu_count_46.sh
qsub Func_accu_count_47.sh
qsub Func_accu_count_48.sh
qsub Func_accu_count_49.sh
qsub Func_accu_count_50.sh
qsub Func_accu_count_51.sh
qsub Func_accu_count_52.sh
qsub Func_accu_count_53.sh
qsub Func_accu_count_54.sh
qsub Func_accu_count_55.sh
qsub Func_accu_count_56.sh
qsub Func_accu_count_57.sh
qsub Func_accu_count_58.sh
qsub Func_accu_count_59.sh
qsub Func_accu_count_60.sh
qsub Func_accu_count_61.sh
qsub Func_accu_count_62.sh
qsub Func_accu_count_63.sh
qsub Func_accu_count_64.sh
qsub Func_accu_count_65.sh
qsub Func_accu_count_66.sh
